<?php

/**
 * BaseAmigoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user1_id
 * @property integer $user2_id
 * @property integer $estado
 * @property sfGuardUserProfile $User1
 * @property sfGuardUser $User2
 * 
 * @method integer            getUser1Id()  Returns the current record's "user1_id" value
 * @method integer            getUser2Id()  Returns the current record's "user2_id" value
 * @method integer            getEstado()   Returns the current record's "estado" value
 * @method sfGuardUserProfile getUser1()    Returns the current record's "User1" value
 * @method sfGuardUser        getUser2()    Returns the current record's "User2" value
 * @method AmigoUsuario       setUser1Id()  Sets the current record's "user1_id" value
 * @method AmigoUsuario       setUser2Id()  Sets the current record's "user2_id" value
 * @method AmigoUsuario       setEstado()   Sets the current record's "estado" value
 * @method AmigoUsuario       setUser1()    Sets the current record's "User1" value
 * @method AmigoUsuario       setUser2()    Sets the current record's "User2" value
 * 
 * @package    rs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmigoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amigo_usuario');
        $this->hasColumn('user1_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('user2_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('estado', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile as User1', array(
             'local' => 'user1_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User2', array(
             'local' => 'user2_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}