<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $fullname
 * @property string $email
 * @property boolean $sexo
 * @property date $fecha_nac
 * @property string $provincia
 * @property string $localidad
 * @property string $avatar
 * @property string $validate
 * @property sfGuardUser $User
 * @property Doctrine_Collection $AmigoUsuario
 * @property Mensaje $Mensaje
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getUserId()       Returns the current record's "user_id" value
 * @method string              getFullname()     Returns the current record's "fullname" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method boolean             getSexo()         Returns the current record's "sexo" value
 * @method date                getFechaNac()     Returns the current record's "fecha_nac" value
 * @method string              getProvincia()    Returns the current record's "provincia" value
 * @method string              getLocalidad()    Returns the current record's "localidad" value
 * @method string              getAvatar()       Returns the current record's "avatar" value
 * @method string              getValidate()     Returns the current record's "validate" value
 * @method sfGuardUser         getUser()         Returns the current record's "User" value
 * @method Doctrine_Collection getAmigoUsuario() Returns the current record's "AmigoUsuario" collection
 * @method Mensaje             getMensaje()      Returns the current record's "Mensaje" value
 * @method sfGuardUserProfile  setId()           Sets the current record's "id" value
 * @method sfGuardUserProfile  setUserId()       Sets the current record's "user_id" value
 * @method sfGuardUserProfile  setFullname()     Sets the current record's "fullname" value
 * @method sfGuardUserProfile  setEmail()        Sets the current record's "email" value
 * @method sfGuardUserProfile  setSexo()         Sets the current record's "sexo" value
 * @method sfGuardUserProfile  setFechaNac()     Sets the current record's "fecha_nac" value
 * @method sfGuardUserProfile  setProvincia()    Sets the current record's "provincia" value
 * @method sfGuardUserProfile  setLocalidad()    Sets the current record's "localidad" value
 * @method sfGuardUserProfile  setAvatar()       Sets the current record's "avatar" value
 * @method sfGuardUserProfile  setValidate()     Sets the current record's "validate" value
 * @method sfGuardUserProfile  setUser()         Sets the current record's "User" value
 * @method sfGuardUserProfile  setAmigoUsuario() Sets the current record's "AmigoUsuario" collection
 * @method sfGuardUserProfile  setMensaje()      Sets the current record's "Mensaje" value
 * 
 * @package    rs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('fullname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sexo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('fecha_nac', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('provincia', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('localidad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('avatar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('validate', 'string', 17, array(
             'type' => 'string',
             'length' => 17,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('AmigoUsuario', array(
             'local' => 'id',
             'foreign' => 'user1_id'));

        $this->hasOne('Mensaje', array(
             'local' => 'id',
             'foreign' => 'sf_guard_user_profile_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'fullname',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}