<?php

/**
 * BaseMensaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_profile_id
 * @property integer $receptor
 * @property integer $tipo
 * @property string $titulo
 * @property string $contenido
 * @property boolean $estado
 * @property sfGuardUserProfile $sfGuardUserProfile
 * 
 * @method integer            getSfGuardUserProfileId()     Returns the current record's "sf_guard_user_profile_id" value
 * @method integer            getReceptor()                 Returns the current record's "receptor" value
 * @method integer            getTipo()                     Returns the current record's "tipo" value
 * @method string             getTitulo()                   Returns the current record's "titulo" value
 * @method string             getContenido()                Returns the current record's "contenido" value
 * @method boolean            getEstado()                   Returns the current record's "estado" value
 * @method sfGuardUserProfile getSfGuardUserProfile()       Returns the current record's "sfGuardUserProfile" value
 * @method Mensaje            setSfGuardUserProfileId()     Sets the current record's "sf_guard_user_profile_id" value
 * @method Mensaje            setReceptor()                 Sets the current record's "receptor" value
 * @method Mensaje            setTipo()                     Sets the current record's "tipo" value
 * @method Mensaje            setTitulo()                   Sets the current record's "titulo" value
 * @method Mensaje            setContenido()                Sets the current record's "contenido" value
 * @method Mensaje            setEstado()                   Sets the current record's "estado" value
 * @method Mensaje            setSfGuardUserProfile()       Sets the current record's "sfGuardUserProfile" value
 * 
 * @package    rs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensaje extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensaje');
        $this->hasColumn('sf_guard_user_profile_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('receptor', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('titulo', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('contenido', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('estado', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile', array(
             'local' => 'sf_guard_user_profile_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}