<?php

/**
 * Mensaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mensaje extends BaseMensaje
{
	
	
	public function getContenidoParcial()
    {

        $texto_mensaje = $this->getContenido();

        $texto_parcial = substr($texto_mensaje, 0, 200);

        $texto_parcial = $texto_parcial.' ... ';

        return $texto_parcial;

    }
	
}
