<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/08/31 20:16:07
sfConfig::add(array(
  'app_sfApplyPlugin_from' => array (
  'email' => 'tirengarfio@gmail.com',
  'fullname' => 'Tirengarfio',
),
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
));
