<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/31 20:16:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rs12;unix_socket=/opt/lampp/var/mysql/mysql.sock',
  'username' => 'root',
  'password' => 'm',
  'name' => 'doctrine',
)),);
