<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/09/01 18:05:36
$this->security = array (
  'settings' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
